package com.example.amasyasut.Datalar

class SiparisData(
    var musteri_ad_soyad: String? = null,
    var siparisi_giren: String? = null,
    var siparis_zamani: Long? = null,
    var siparis_teslim_zamani: Long? = null,
    var siparis_teslim_tarihi: Long? = null,
    var siparis_adres: String? = null,
    var siparis_notu: String? = null,
    var siparis_mah: String? = null,
    var siparis_key: String? = null,
    var siparis_apartman: String? = null,
    var siparis_tel: String? = null,
    var musteri_zkonum: Boolean? = null,
    var musteri_zlat: Double? = null,
    var musteri_zlong: Double? = null,
    var zz_3litre: String? = null,
    var zz_3litreFiyat: String? = null,
    var zz_5litre: String? = null,
    var zz_5litreFiyat: String? = null,
    var zz_Bp500: String? = null,
    var zz_Bp500Fiyat: String? = null,
    var zz_Bp800: String? = null,
    var zz_Bp800Fiyat: String? = null,
    var zz_Bp5Kg: String? = null,
    var zz_Bp5KgFiyat: String? = null,
    var zz_Bp17Kg: String? = null,
    var zz_Bp17KgFiyat: String? = null,
    var zz_Kasar400Gr: String? = null,
    var zz_Kasar400GrFiyat: String? = null,
    var zz_Kasar700Gr: String? = null,
    var zz_Kasar700GrFiyat: String? = null,
    var zz_Kasar1KgGr: String? = null,
    var zz_Kasar1KgGrFiyat: String? = null,
    var zz_Kasar2KgPide: String? = null,
    var zz_Kasar2KgPideFiyat: String? = null,
    var zz_Kasar2KgTost: String? = null,
    var zz_Kasar2KgTostFiyat: String? = null,


    var zz_Koy5Kg: String? = null,
    var zz_Koy5KgFiyat: String? = null,
    var zz_Koy15Kg: String? = null,
    var zz_Koy15KgFiyat: String? = null,
    var zz_Tulum250: String? = null,
    var zz_Tulum250Fiyat: String? = null,
    var zz_CerkezPeynir: String? = null,
    var zz_CerkezPeynirFiyat: String? = null,
    var zz_Lor9Kg: String? = null,
    var zz_Lor9KgFiyat: String? = null,
    var zz_Cokelek: String? = null,
    var zz_CokelekFiyat: String? = null,
    var zz_YogurtTam200: String? = null,
    var zz_YogurtTam200Fiyat: String? = null,
    var zz_YogurtTam500: String? = null,
    var zz_YogurtTam500Fiyat: String? = null,
    var zz_YogurtTam1250: String? = null,
    var zz_YogurtTam1250Fiyat: String? = null,
    var zz_YogurtTam2Kg: String? = null,
    var zz_YogurtTam2KgFiyat: String? = null,
    var zz_YogurtTam9Kg: String? = null,
    var zz_YogurtTam9KgFiyat: String? = null,
    var zz_YogurtYarım200V: String? = null,
    var zz_YogurtYarım200VFiyat: String? = null,
    var zz_YogurtYarım10KgV: String? = null,
    var zz_YogurtYarım10KgVFiyat: String? = null,
    var zz_YogurtYarım2KgDM: String? = null,
    var zz_YogurtYarım2KgDMFiyat: String? = null,
    var zz_YogurtYarım3KgDM: String? = null,
    var zz_YogurtYarım3KgDMFiyat: String? = null,
    var zz_YogurtYarım4KgDM: String? = null,
    var zz_YogurtYarım4KgDMFiyat: String? = null,
    var zz_YogurtYarım10KgDM: String? = null,
    var zz_YogurtYarım10KgDMFiyat: String? = null,
    var zz_YogurtAz10KgOzel: String? = null,
    var zz_YogurtAz10KgOzelFiyat: String? = null,
    var zz_YogurtSuzme900: String? = null,
    var zz_YogurtSuzme900Fiyat: String? = null,
    var zz_YogurtSuzme5Kg: String? = null,
    var zz_YogurtSuzme5KgFiyat: String? = null,
    var zz_Yogurt2750KgTava: String? = null,
    var zz_Yogurt2750KgTavaFiyat: String? = null,


    var zz_Ayran1Lt: String? = null,
    var zz_Ayran1LtFiyat: String? = null,
    var zz_Ayran290: String? = null,
    var zz_Ayran290Fiyat: String? = null,
    var zz_Ayran220: String? = null,
    var zz_Ayran220Fiyat: String? = null,
    var zz_Ayran200: String? = null,
    var zz_Ayran200Fiyat: String? = null,
    var zz_Ayran180: String? = null,
    var zz_Ayran180Fiyat: String? = null,
    var zz_Ayran170: String? = null,
    var zz_Ayran170Fiyat: String? = null,
    var zz_Ayran150: String? = null,
    var zz_Ayran150Fiyat: String? = null,


    var zz_Tereyag500: String? = null,
    var zz_Tereyag500Fiyat: String? = null,
    var zz_Tereyag1Kg: String? = null,
    var zz_Tereyag1KgFiyat: String? = null,
    var zz_Tereyag1800: String? = null,
    var zz_Tereyag1800Fiyat: String? = null,
    var zz_Tereyag1KgKoy: String? = null,
    var zz_Tereyag1KgKoyFiyat: String? = null,
    var zz_Kaymak200: String? = null,
    var zz_Kaymak200Fiyat: String? = null


) {


}